management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
        exclude: env,configprops,beans,mappings,heapdump,threaddump,loggers,shutdown,caches,scheduledtasks,startup
